### ISSUE TITLE
Issue with embedded font

### ISSUE THREAD

**Issue by manhbui21** [plutext/docx4j#289] opened 2018-03-21 08:35 UTC
Hi, I am using docx4j 3.3.6 in my app. It works almost perfectly until i got a problem with a document that had embedded Ubuntu font family. When I try to convert it to PDF, the console throws an exception "Exception writing Document to OutputStream: java.io.FileNotFoundException: C:\Users\abc\\.docx4all\temporary embedded fonts\1521620957690-Ubuntu-bold.ttf (The system cannot find the file specified)". I tried to open that directory but I saw too many Ubuntu-bold.ttf file with different prefix number. What should I do in this case?

**Comment by l0v3w4v3** [comment] 2018-04-04 07:45
@plutext could you consider this case please?

**Comment by mchater** [comment] 2019-04-05 08:50
Hello,
Have you found a solution for this issue because i have the same problem.
Thank you!

**Comment by andriydm** [comment] 2019-04-25 16:57
Hi,
I am also have the same problem. I am using docx4j 6.1.2 Debugging a little bit I have found that the class ObfuscatedFontPart has finalize() method which is called by Finilezer before garbage collector destroys the instance. Finalize method deletes font file stored in tmpFontDir. In my case at least 3 files (with different filenamePrefix) for same font were created. My code is very simple, I just read docx file and try to convert it to PDF. 
`
WordprocessingMLPackage wordMLPackage = Docx4J.load(new java.io.File(fileDocx));
OutputStream os = new ByteArrayOutputStream();
Docx4J.toPDF(wordMLPackage, os);
`

**Comment by 18876293672** [comment] 2019-09-16 06:28
i"am cry when i see this problem. i dont know how to solve it .

**Comment by 16thREST** [comment] 2020-08-27 11:48
Confirmed. Same here. Here is outcome of debugging: 
- fonts are extracted 3 times from the source docx with embedded fonts. Each time with new prefix (1598526207499-Calibri Light.ttf). This happens during SINGLE docx to PDF conversion. 
- Unfortunately after 3rd extraction, during PDF build, in LayoutMasterSetBuilder.fixExtents method all extracted font files  are being deleted via FontTablePart.deleteEmbeddedFontTempFiles. 
- FontTablePart.deleteEmbeddedFontTempFiles calls ObfuscatedFontPart.deleteEmbeddedFontTempFiles which even has a comment 
"// this isn't really necessary given finalize(), but this gets rid of them a bit sooner than GC may happen
 // (when it is invoked first; sometimes it isn't - note this is a static method)"
- Then Apache FOP tries to read such no longer existing font file and throws an error.

Could you fix this? It could be sufficient enough (for now) just to not call FontTablePart.deleteEmbeddedFontTempFiles and leave the clean up to GC. But long term solution shouldn't rely on GC and files should be really clean up after full PDF generation.

**Comment by plutext** [comment] 2020-12-05 01:18
The fonts are currently extracted 3 times:

1. setFontMapper does processEmbeddings
2. (optional) deep copy of source docx
3. if there are headers/footers (LayoutMasterSet)

It should only be done once, so we'll need to fix this: https://github.com/plutext/docx4j/issues/422

The fonts are extracted using System.currentTimeMillis as a prefix.

Which set are you guys finding is deleted too early?  I guess the set being used for header/footer generation, so I'll remove https://github.com/plutext/docx4j/blob/master/docx4j-export-fo/src/main/java/org/docx4j/convert/out/fo/LayoutMasterSetBuilder.java#L153

https://github.com/plutext/docx4j/commit/29e3e2971fc86a8d0f64af30ca254ce2e5c59028

**Comment by ashtonbatty** [comment] 2020-12-08 01:25
Using System.currentTimeMillis for a prefix is dangerous in a multithreaded application. Ideally you should be using Java's NIO.2 API for creating temporary files, to avoid race conditions (Files.createTempDirectory() and Files.createTempFile(), https://docs.oracle.com/javase/8/docs/api/index.html?java/nio/file/Files.html )

Anyway, is there any chance you could push out a 11.x release with the early delete fix in it too?

Thanks.

**Comment by Fufusulier** [comment] 2021-03-15 15:11
Hi there,
I have the issue with the version 11.2.8 of docx4j. The issue has been opened for quite a long time now. Is the project under active development?

`org.apache.fop.pdf.PDFFactory            : Failed to embed font [org.apache.fop.fonts.LazyFont@739e855a{Calibri Bold}{metrics-url=null,embed-url=file:/tmp/1615820055042-Calibri-bold.ttf,kerning=true,advanced=true}] Calibri-Bold
java.io.FileNotFoundException: /tmp/1615820055042-Calibri-bold.ttf (No such file or directory)`


Thank you,
Yannick

**Comment by plutext** [comment] 2021-03-15 22:36
This was fixed in 8.2.6, and the fix should be present in 11.2.8.    @Fufusulier your issue is likely different, so please create a new issue including steps to reproduce.

**Closed by plutext** 2021-03-15 22:36 UTC

**Comment by ljgp** [comment] 2021-07-01 13:50
I am using 8.2.8 and still run into this issue on Unix, not Windows. My conclusion is that PhysicalFonts registers a temporary embedded font as physical, after looking at the logs:

01/07/2021:14:38:47 org.docx4j.openpackaging.parts.WordprocessingML.FontTablePart | Writing temp embedded fonts 1625143127810
01/07/2021:14:38:47 org.docx4j.openpackaging.parts.WordprocessingML.ObfuscatedFontPart | Loading from: /opt/jboss/.docx4all/temporary embedded fonts/1625143127810-Calibri.ttf
01/07/2021:14:38:47 org.docx4j.fonts.PhysicalFonts | Processing physical font: file:/opt/jboss/.docx4all/temporary embedded fonts/1625143127810-calibri.ttf
01/07/2021:14:38:47 org.docx4j.openpackaging.parts.WordprocessingML.ObfuscatedFontPart | Loading from: /opt/jboss/.docx4all/temporary embedded fonts/1625143127810-Times New Roman.ttf
<fop version="1.0"><strict-configuration>true</strict-configuration><renderers><renderer mime="application/pdf"><fonts><font embed-url="file:/opt/jboss/.docx4all/temporary embedded fonts/1625143127810-Calibri.ttf"><font-triplet name="Calibri" style="normal" weight="normal"/></font></fonts></renderer></renderers></fop>
01/07/2021:14:38:49 org.docx4j.openpackaging.parts.WordprocessingML.FontTablePart | Deleting temp embedded fonts 1625143127810
01/07/2021:14:40:07 org.apache.fop.fonts.LazyFont | Failed to read font file file:/opt/jboss/.docx4all/temporary%20embedded%20fonts/1625143127810-Calibri.ttf /opt/jboss/.docx4all/temporary embedded fonts/1625143127810-Calibri.ttf (No such file or directory)
java.io.FileNotFoundException: /opt/jboss/.docx4all/temporary embedded fonts/1625143127810-Calibri.ttf (No such file or directory)
