### ISSUE TITLE
Going from 3.3.0 to 3.3.1 breaks Docx4J.bind

### ISSUE THREAD

**Issue by roytmana** [plutext/docx4j#215] opened 2016-08-31 21:03 UTC
Docx4J.bind(wordMLPackage, serialize(caseData, jaxbContext), Docx4J.FLAG_BIND_INSERT_XML + Docx4J.FLAG_BIND_BIND_XML);

here is how my caseData is serialized:

```
<case xmlns="http://gctrack.gao.gov/templates/case-data">
    <fileNumber>xxxx</fileNumber>
    <caseNumber>5</caseNumber>
....
</case>
```

```
org.docx4j.openpackaging.exceptions.Docx4JException: Exception executing /ns0:case[1]/ns0:bnumber[1]
	at org.docx4j.openpackaging.parts.XmlPart.cachedXPathGetString(XmlPart.java:241)
	at org.docx4j.openpackaging.parts.CustomXmlDataStoragePart.cachedXPathGetString(CustomXmlDataStoragePart.java:166)
	at org.docx4j.model.datastorage.BindingHandler.xpathGetString(BindingHandler.java:319)
	at org.docx4j.model.datastorage.BindingTraverserXSLT.xpathGenerateRuns(BindingTraverserXSLT.java:925)
	at org.docx4j.model.datastorage.BindingTraverserXSLT.xpathGenerateRuns(BindingTraverserXSLT.java:873)
:
org.apache.xalan.extensions.ExtensionHandlerJavaPackage.callFunction(ExtensionHandlerJavaPackage.java:343)
	at org.apache.xalan.extensions.ExtensionHandlerJavaPackage.callFunction(ExtensionHandlerJavaPackage.java:440)
	at org.apache.xalan.extensions.ExtensionsTable.extFunction(ExtensionsTable.java:222)
	at org.apache.xalan.transformer.TransformerImpl.extFunction(TransformerImpl.java:475)
	at org.apache.xpath.functions.FuncExtFunction.execute(FuncExtFunction.java:208)
:
	at org.docx4j.XmlUtils.transform(XmlUtils.java:1275)
	at org.docx4j.XmlUtils.transform(XmlUtils.java:1100)
	at org.docx4j.model.datastorage.BindingTraverserXSLT.traverseToBind(BindingTraverserXSLT.java:172)
	at org.docx4j.model.datastorage.BindingHandler.applyBindings(BindingHandler.java:259)
	at org.docx4j.model.datastorage.BindingHandler.applyBindings(BindingHandler.java:189)
	at org.docx4j.Docx4J.bind(Docx4J.java:426)
	at org.docx4j.Docx4J.bind(Docx4J.java:373)
	at org.docx4j.Docx4J.bind(Docx4J.java:347)
	at gov.gao.ogc.gctrack.web.rs.TemplateResource.createDocument(TemplateResource.java:130)
:
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
:
Caused by: org.apache.xpath.domapi.XPathStylesheetDOM3Exception: Prefix must resolve to a namespace: ns0
	at org.apache.xpath.compiler.XPathParser.errorForDOM3(XPathParser.java:655)
	at org.apache.xpath.compiler.Lexer.mapNSTokens(Lexer.java:647)
	at org.apache.xpath.compiler.Lexer.tokenize(Lexer.java:274)
	at org.apache.xpath.compiler.Lexer.tokenize(Lexer.java:98)
	at org.apache.xpath.compiler.XPathParser.initXPath(XPathParser.java:112)
	at org.apache.xpath.XPath.<init>(XPath.java:178)
	at org.apache.xpath.CachedXPathAPI.eval(CachedXPathAPI.java:288)
	at org.apache.xpath.CachedXPathAPI.selectNodeIterator(CachedXPathAPI.java:183)
	at org.apache.xpath.CachedXPathAPI.selectSingleNode(CachedXPathAPI.java:144)
	at org.apache.xpath.CachedXPathAPI.selectSingleNode(CachedXPathAPI.java:124)
	at org.docx4j.openpackaging.parts.XmlPart.cachedXPathGetString(XmlPart.java:212)
	... 116 more
ERROR 31/08/16 16:54:12 docx4j.XmlUtils - org.docx4j.model.datastorage.InputIntegrityException: Exception executing /ns0:case[1]/ns0:bnumber[1]
; Line#: 787; Column#: 27
javax.xml.transform.TransformerException: org.docx4j.model.datastorage.InputIntegrityException: Exception executing /ns0:case[1]/ns0:bnumber[1]

Caused by: org.docx4j.model.datastorage.InputIntegrityException: Exception executing /ns0:case[1]/ns0:bnumber[1]
	at org.docx4j.model.datastorage.BindingHandler.xpathGetString(BindingHandler.java:337)
	at org.docx4j.model.datastorage.BindingTraverserXSLT.xpathGenerateRuns(BindingTraverserXSLT.java:925)
	at org.docx4j.model.datastorage.BindingTraverserXSLT.xpathGenerateRuns(BindingTraverserXSLT.java:873)

**Comment by plutext** [comment] 2016-09-01 02:14
It is caused by this stuff https://github.com/plutext/docx4j/commit/342b1b4b1f52f394e254609a1fe979d2968b6a5d

I'll need to create a test case to fix it.

In the meantime, if you look towards the start of your log file, what does org.docx4j.XmlUtils log at INFO level?  I'm looking for something like:

INFO org.docx4j.XmlUtils .<clinit> line 193 - setProperty com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
INFO org.docx4j.XmlUtils .<clinit> line 206 - actual: com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
INFO org.docx4j.XmlUtils .<clinit> line 244 - setProperty com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
INFO org.docx4j.XmlUtils .<clinit> line 260 - actual: com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl

**Comment by roytmana** [comment] 2016-09-01 02:28
```
WARN  31/08/16 22:24:11 utils.ResourceUtils - Couldn't get resource: docx4j.properties
WARN  31/08/16 22:24:11 docx4j.Docx4jProperties - Couldn't find/read docx4j.properties; docx4j.properties not found via classloader.
INFO  31/08/16 22:24:11 docx4j.XmlUtils - setProperty com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
INFO  31/08/16 22:24:11 docx4j.XmlUtils - actual: com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
INFO  31/08/16 22:24:11 docx4j.XmlUtils - setProperty com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
INFO  31/08/16 22:24:11 docx4j.XmlUtils - actual: com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
WARN  31/08/16 22:24:11 io3.Load3 - No JAXB model for this CustomXmlDataStorage part; null
WARN  31/08/16 22:24:11 datastorage.BindingHandler - OpenDoPE XPaths part missing
INFO  31/08/16 22:24:11 docx4j.XmlUtils - Using org.apache.xalan.transformer.TransformerImpl
ERROR 31/08/16 22:24:11 datastorage.BindingHandler - Exception executing /ns0:case[1]/ns0:bnumber[1]
```

**Comment by plutext** [comment] 2016-09-03 04:46
Fixed by https://github.com/plutext/docx4j/commit/391a50687b0c36dfc847ca4d7f19cf2ad0c2772c

**Closed by plutext** 2016-09-03 04:46 UTC
